#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "develop" ] || [ "$branch" = "main" ];
then
  echo "You can't commit directly to "$branch" branch\nSWITCH TO YOUR WORKING BRANCH ! ! !"
  exit 1
else
yarn lint
fi

